apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: phi-chat
  namespace: llm-serving
spec:
  # Send 25% traffic to the new revision created from this updated predictor.
  # Remaining 75% automatically stays on previous ready revision.
  canaryTrafficPercent: 25

  predictor:
    serviceAccountName: vllm-serving
    nodeSelector:
      eks.amazonaws.com/nodegroup: k8s-llm-serving-gpu-dev
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule

    containers:
      - name: kserve-container
        image: vllm/vllm-openai:v0.25.1
        args:
          - /models/microsoft/Phi-3-mini-4k-instruct/main
          - --served-model-name
          - phi-3
          - --host
          - 0.0.0.0
          - --port
          - "8000"
          - --gpu-memory-utilization
          - "0.90"
          - --max-num-seqs
          - "16"
        resources:
          requests:
            cpu: "1200m"
            memory: "4Gi"
            nvidia.com/gpu: "1"
          limits:
            cpu: "2000m"
            memory: "7Gi"
            nvidia.com/gpu: "1"

        volumeMounts:
          - name: model-cache
            mountPath: /models
            readOnly: true

    volumes:
      - name: model-cache
        hostPath:
          path: /var/lib/llm-model-cache
          type: Directory