#!/usr/bin/env python3

"""
statistics.py

Purpose
-------
Analyse request-level benchmark results generated by loadgen.py.

This script is the CLIENT-SIDE source of truth.

It computes:

    - Request totals
    - Successes / errors
    - Success and error rates
    - RPS (requests per second)
    - Average latency
    - Min / Max latency
    - P50 / P90 / P95 / P99 latency

Input
-----
Request-level JSONL file produced by loadgen.py.

One request per line:

{
    "request_id": 123,
    "timestamp": 1753911111,
    "status": 200,
    "success": true,
    "latency_ms": 2034.5,
    "error": null
}

Benchmark summary file produced by loadgen.py:

{
    "run_start": 1753911000,
    "run_end": 1753911480,
    ...
}

Output
------
Machine-readable JSON summary.

Example:

{
    "requests_total": 10561,
    "successes": 10561,
    "errors": 0,
    "success_rate_pct": 100.0,
    "error_rate_pct": 0.0,
    "duration_seconds": 480,
    "rps": 22.0,
    "latency_avg_ms": 1994.2,
    "latency_min_ms": 1884.1,
    "latency_max_ms": 2440.3,
    "latency_p50_ms": 1980.4,
    "latency_p90_ms": 2056.8,
    "latency_p95_ms": 2112.9,
    "latency_p99_ms": 2280.1
}
"""

import argparse
import json
import statistics
from pathlib import Path


def percentile(values, pct):
    """
    Calculate percentile using linear interpolation.

    Used for:
        - P50
        - P90
        - P95
        - P99
    """

    if not values:
        return 0.0

    values = sorted(values)

    if len(values) == 1:
        return float(values[0])

    k = (len(values) - 1) * (pct / 100)

    f = int(k)
    c = min(f + 1, len(values) - 1)

    if f == c:
        return float(values[f])

    return float(
        values[f] + (values[c] - values[f]) * (k - f)
    )


def main():
    """
    Main entry point.

    Steps:

        1. Read request-level JSONL.
        2. Read benchmark summary JSON.
        3. Aggregate latency and status data.
        4. Calculate benchmark statistics.
        5. Emit machine-readable JSON.
    """

    parser = argparse.ArgumentParser(
        description=(
            "Generate benchmark statistics from "
            "request-level JSONL results."
        )
    )

    parser.add_argument(
        "--input",
        required=True,
        help="Request-level JSONL file"
    )

    parser.add_argument(
        "--summary-file",
        required=True,
        help="Benchmark summary JSON from loadgen.py"
    )

    args = parser.parse_args()

    input_file = Path(args.input)
    summary_file = Path(args.summary_file)

    #
    # Validate required files.
    #
    if not input_file.exists():
        raise FileNotFoundError(
            f"Request file not found: {input_file}"
        )

    if not summary_file.exists():
        raise FileNotFoundError(
            f"Summary file not found: {summary_file}"
        )

    #
    # Load benchmark summary.
    #
    # We use run_start/run_end rather than
    # inferring duration from request timestamps.
    #
    with summary_file.open(
        "r",
        encoding="utf-8",
    ) as fh:

        benchmark_summary = json.load(fh)

    run_start = benchmark_summary["run_start"]
    run_end = benchmark_summary["run_end"]

    duration_seconds = max(
        run_end - run_start,
        1,
    )

    #
    # Aggregation containers.
    #
    latencies = []

    requests_total = 0
    successes = 0
    errors = 0

    #
    # Read all request records.
    #
    with input_file.open(
        "r",
        encoding="utf-8",
    ) as fh:

        for line in fh:

            line = line.strip()

            if not line:
                continue

            record = json.loads(line)

            requests_total += 1

            if record.get("success"):
                successes += 1
            else:
                errors += 1

            latency = record.get("latency_ms")

            if latency is not None:
                latencies.append(
                    float(latency)
                )

    #
    # Success / error rates.
    #
    success_rate = (
        (successes / requests_total) * 100
        if requests_total > 0
        else 0
    )

    error_rate = (
        (errors / requests_total) * 100
        if requests_total > 0
        else 0
    )

    #
    # Client-observed throughput.
    #
    rps = (
        requests_total / duration_seconds
    )

    summary = {

        #
        # Request counts.
        #
        "requests_total":
            requests_total,

        "successes":
            successes,

        "errors":
            errors,

        #
        # Success statistics.
        #
        "success_rate_pct":
            round(success_rate, 3),

        "error_rate_pct":
            round(error_rate, 3),

        #
        # Benchmark runtime.
        #
        "duration_seconds":
            duration_seconds,

        "rps":
            round(rps, 3),

        #
        # Latency distribution.
        #
        "latency_avg_ms":
            round(
                statistics.mean(latencies),
                3,
            ) if latencies else 0,

        "latency_min_ms":
            round(
                min(latencies),
                3,
            ) if latencies else 0,

        "latency_max_ms":
            round(
                max(latencies),
                3,
            ) if latencies else 0,

        "latency_p50_ms":
            round(
                percentile(latencies, 50),
                3,
            ) if latencies else 0,

        "latency_p90_ms":
            round(
                percentile(latencies, 90),
                3,
            ) if latencies else 0,

        "latency_p95_ms":
            round(
                percentile(latencies, 95),
                3,
            ) if latencies else 0,

        "latency_p99_ms":
            round(
                percentile(latencies, 99),
                3,
            ) if latencies else 0,
    }

    print(
        json.dumps(
            summary,
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
